import "server-only";

import {
  getTableDef,
  isDashboardTableId,
  isNonEditableIdentityColumn,
  TABLE_CATALOG,
  TABLE_IDS,
} from "@/lib/dashboard/tableCatalog";
import { listLiveColumns } from "@/lib/dashboard/schema";
import type {
  ColumnDef,
  DashboardTableId,
  FkOption,
  TableRow,
  TableSummaryItem,
} from "@/lib/dashboard/types/tables";
import { createSupabaseAdminClient } from "@/lib/supabase";

const DEFAULT_PAGE_SIZE = 25;
const MAX_PAGE_SIZE = 100;

function parsePage(value: string | null) {
  const page = Number(value ?? "1");
  return Number.isFinite(page) && page > 0 ? Math.floor(page) : 1;
}

function parsePageSize(value: string | null) {
  const size = Number(value ?? DEFAULT_PAGE_SIZE);
  if (!Number.isFinite(size) || size < 1) return DEFAULT_PAGE_SIZE;
  return Math.min(Math.floor(size), MAX_PAGE_SIZE);
}

function emptyToNull(value: unknown) {
  if (typeof value === "string" && value.trim() === "") return null;
  return value;
}

function coerceValue(column: ColumnDef, value: unknown) {
  const normalized = emptyToNull(value);
  if (normalized == null) return null;

  switch (column.type) {
    case "boolean":
      if (typeof normalized === "boolean") return normalized;
      if (normalized === "true" || normalized === "1") return true;
      if (normalized === "false" || normalized === "0") return false;
      return Boolean(normalized);
    case "number": {
      const numberValue = Number(normalized);
      if (!Number.isFinite(numberValue)) {
        throw new Error(`Invalid number for ${column.key}.`);
      }
      return numberValue;
    }
    case "uuid":
    case "fk":
    case "text":
    case "longtext":
    case "date":
    case "datetime":
      return String(normalized);
    default:
      return normalized;
  }
}

async function buildPayload(
  table: DashboardTableId,
  body: Record<string, unknown>,
  mode: "create" | "edit",
) {
  const columns = await listLiveColumns(table);
  const payload: Record<string, unknown> = {};

  for (const column of columns) {
    if (isNonEditableIdentityColumn(column, mode)) continue;
    if (!(column.key in body)) {
      if (mode === "create" && column.required && !column.autoGenerated) {
        throw new Error(`Missing required field: ${column.key}.`);
      }
      continue;
    }

    const value = coerceValue(column, body[column.key]);
    if (value == null && column.required) {
      throw new Error(`Missing required field: ${column.key}.`);
    }
    if (value == null && !column.required) continue;
    payload[column.key] = value;
  }

  return payload;
}

export function resolveTableId(raw: string): DashboardTableId {
  if (!isDashboardTableId(raw)) {
    throw new Error(`Unknown table: ${raw}.`);
  }
  return raw;
}

export async function getTableSummaries(): Promise<TableSummaryItem[]> {
  const supabase = createSupabaseAdminClient();

  const results = await Promise.all(
    TABLE_IDS.map(async (id) => {
      const def = TABLE_CATALOG[id];
      const { count, error } = await supabase
        .from(id)
        .select("id", { count: "exact", head: true });

      if (error) {
        throw new Error(`Failed to count ${id}: ${error.message}`);
      }

      return {
        id,
        name: def.name,
        description: def.description,
        count: count ?? 0,
      };
    }),
  );

  return results;
}

export async function listTableRows(input: {
  table: DashboardTableId;
  page?: number;
  pageSize?: number;
  search?: string;
}) {
  const supabase = createSupabaseAdminClient();
  const def = getTableDef(input.table);
  const columns = await listLiveColumns(input.table);
  const page = input.page && input.page > 0 ? input.page : 1;
  const pageSize =
    input.pageSize && input.pageSize > 0
      ? Math.min(input.pageSize, MAX_PAGE_SIZE)
      : DEFAULT_PAGE_SIZE;
  const from = (page - 1) * pageSize;
  const to = from + pageSize - 1;

  let query = supabase
    .from(input.table)
    .select("*", { count: "exact" })
    .range(from, to);

  if (def.defaultOrderBy) {
    query = query.order(def.defaultOrderBy.column, {
      ascending: def.defaultOrderBy.ascending ?? true,
    });
  }

  const search = input.search?.trim();
  if (search) {
    const textColumns = columns
      .filter(
        (column) =>
          column.type === "text" ||
          column.type === "longtext" ||
          column.type === "uuid",
      )
      .map((column) => column.key);

    if (textColumns.length > 0) {
      const orFilter = textColumns
        .map((key) => `${key}.ilike.%${search}%`)
        .join(",");
      query = query.or(orFilter);
    }
  }

  const { data, error, count } = await query;
  if (error) {
    throw new Error(`Failed to list ${input.table}: ${error.message}`);
  }

  return {
    rows: (data ?? []) as TableRow[],
    columns,
    total: count ?? 0,
    page,
    pageSize,
  };
}

export async function createTableRow(
  table: DashboardTableId,
  body: Record<string, unknown>,
) {
  const supabase = createSupabaseAdminClient();
  const payload = await buildPayload(table, body, "create");
  const { data, error } = await supabase
    .from(table)
    .insert(payload)
    .select("*")
    .single();

  if (error) {
    throw new Error(`Failed to create row in ${table}: ${error.message}`);
  }

  return data as TableRow;
}

export async function updateTableRow(
  table: DashboardTableId,
  id: string,
  body: Record<string, unknown>,
) {
  const supabase = createSupabaseAdminClient();
  const payload = await buildPayload(table, body, "edit");
  const { data, error } = await supabase
    .from(table)
    .update(payload)
    .eq("id", id)
    .select("*")
    .single();

  if (error) {
    throw new Error(`Failed to update row in ${table}: ${error.message}`);
  }

  return data as TableRow;
}

export async function deleteTableRow(table: DashboardTableId, id: string) {
  const supabase = createSupabaseAdminClient();
  const { error } = await supabase.from(table).delete().eq("id", id);

  if (error) {
    throw new Error(`Failed to delete row in ${table}: ${error.message}`);
  }
}

export async function listFkOptions(
  table: DashboardTableId,
  options?: { valueKey?: string; labelKey?: string },
): Promise<FkOption[]> {
  const valueKey = options?.valueKey?.trim() || "id";
  const resolvedLabelKey = options?.labelKey?.trim()
    ? options.labelKey.trim()
    : table === "workbooks"
      ? "workbook_name"
      : table === "workbook_pages"
        ? "page_name"
        : table === "report_queries"
          ? "report_code"
          : table === "powerbi_groups" || table === "powerbi_datasets"
            ? "name"
            : valueKey;

  const supabase = createSupabaseAdminClient();
  const { data, error } = await supabase
    .from(table)
    .select("*")
    .order(resolvedLabelKey, { ascending: true })
    .limit(500);

  if (error) {
    throw new Error(`Failed to load options for ${table}: ${error.message}`);
  }

  return ((data ?? []) as TableRow[])
    .map((row) => {
      const id = row[valueKey];
      if (id == null) return null;
      return {
        id: String(id),
        label: String(row[resolvedLabelKey] ?? id),
      };
    })
    .filter((option): option is FkOption => option != null);
}

export function parseListQuery(searchParams: URLSearchParams) {
  return {
    page: parsePage(searchParams.get("page")),
    pageSize: parsePageSize(searchParams.get("pageSize")),
    search: searchParams.get("search")?.trim() || undefined,
  };
}
