import "server-only";

import {
  getColumnOverride,
  getTableDef,
  isDashboardTableId,
} from "@/lib/dashboard/tableCatalog";
import type {
  ColumnDef,
  ColumnType,
  DashboardTableId,
} from "@/lib/dashboard/types/tables";
import { createSupabaseAdminClient } from "@/lib/supabase";

export type DbColumnRow = {
  column_name: string;
  data_type: string;
  udt_name: string;
  is_nullable: string;
  column_default: string | null;
  ordinal_position: number;
  is_primary_key: boolean;
  foreign_table: string | null;
  foreign_column: string | null;
};

export const ADDABLE_COLUMN_TYPES: Array<{
  value: Exclude<ColumnType, "fk">;
  label: string;
}> = [
  { value: "text", label: "Text" },
  { value: "longtext", label: "Long text" },
  { value: "boolean", label: "Boolean" },
  { value: "number", label: "Number" },
  { value: "date", label: "Date" },
  { value: "datetime", label: "Date & time" },
  { value: "uuid", label: "UUID" },
];

const SYSTEM_TIMESTAMP_COLUMNS = new Set(["created_at", "updated_at"]);

export const SCHEMA_RPC_HINT =
  "Schema RPCs are missing. Run supabase/migrations/20260720000000_dashboard_schema_rpcs.sql in the Supabase SQL editor.";

function humanizeColumnName(key: string) {
  return key
    .replace(/_/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function mapPostgresType(row: DbColumnRow): ColumnType {
  const udt = row.udt_name.toLowerCase();
  const dataType = row.data_type.toLowerCase();

  if (udt === "uuid" || dataType === "uuid") return "uuid";
  if (udt === "bool" || dataType === "boolean") return "boolean";
  if (
    udt === "int2" ||
    udt === "int4" ||
    udt === "int8" ||
    udt === "numeric" ||
    udt === "float4" ||
    udt === "float8" ||
    dataType.includes("int") ||
    dataType === "numeric" ||
    dataType === "real" ||
    dataType === "double precision"
  ) {
    return "number";
  }
  if (udt === "date" || dataType === "date") return "date";
  if (
    udt.startsWith("timestamp") ||
    dataType.startsWith("timestamp") ||
    dataType === "timestamptz"
  ) {
    return "datetime";
  }
  return "text";
}

function isAutoGenerated(row: DbColumnRow) {
  const defaultValue = row.column_default?.toLowerCase() ?? "";
  return (
    defaultValue.includes("gen_random_uuid") ||
    defaultValue.includes("uuid_generate") ||
    defaultValue.includes("nextval(") ||
    defaultValue.includes("now()")
  );
}

function guessTypeFromValue(value: unknown): ColumnType {
  if (typeof value === "boolean") return "boolean";
  if (typeof value === "number") return "number";
  if (typeof value === "string") {
    if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return "date";
    if (/^\d{4}-\d{2}-\d{2}T/.test(value)) return "datetime";
    if (
      /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
        value,
      )
    ) {
      return "uuid";
    }
  }
  return "text";
}

export function mapDbColumnToDef(
  table: DashboardTableId,
  row: DbColumnRow,
): ColumnDef {
  const key = row.column_name;
  const override = getColumnOverride(table, key);
  const baseType = mapPostgresType(row);
  const fkTable =
    (row.foreign_table && isDashboardTableId(row.foreign_table)
      ? row.foreign_table
      : undefined) ?? override?.fkTable;
  const hasFk = Boolean(fkTable);

  return {
    key,
    label: override?.label ?? humanizeColumnName(key),
    type: hasFk ? "fk" : (override?.type ?? baseType),
    required:
      override?.required ??
      (row.is_nullable === "NO" && !isAutoGenerated(row)),
    primaryKey: override?.primaryKey ?? row.is_primary_key,
    autoGenerated:
      override?.autoGenerated ??
      ((row.is_primary_key || key.toLowerCase() === "id") &&
        isAutoGenerated(row)),
    readOnly:
      override?.readOnly ?? SYSTEM_TIMESTAMP_COLUMNS.has(key.toLowerCase()),
    createOnly: override?.createOnly,
    protected:
      override?.protected ??
      (row.is_primary_key ||
        SYSTEM_TIMESTAMP_COLUMNS.has(key.toLowerCase())),
    fkTable,
    fkValueKey: override?.fkValueKey ?? row.foreign_column ?? undefined,
    fkLabelKey: override?.fkLabelKey,
  };
}

function isMissingRpcError(error: { message?: string; code?: string } | null) {
  if (!error) return false;
  const normalized = `${error.code ?? ""} ${error.message ?? ""}`.toLowerCase();
  return (
    normalized.includes("pgrst202") ||
    normalized.includes("could not find the function") ||
    normalized.includes("dashboard_list_columns") ||
    normalized.includes("dashboard_add_column") ||
    normalized.includes("dashboard_drop_column") ||
    normalized.includes("schema cache")
  );
}

async function inferColumnsFromRows(
  table: DashboardTableId,
): Promise<ColumnDef[]> {
  const supabase = createSupabaseAdminClient();
  const { data, error } = await supabase.from(table).select("*").limit(5);
  if (error) {
    throw new Error(`Failed to infer columns for ${table}: ${error.message}`);
  }

  const rows = (data ?? []) as Record<string, unknown>[];
  const keySet = new Set<string>();
  for (const row of rows) {
    for (const key of Object.keys(row)) keySet.add(key);
  }

  const overrides = getTableDef(table).columnOverrides ?? [];
  for (const override of overrides) keySet.add(override.key);

  if (keySet.size === 0) {
    keySet.add("id");
  }

  return [...keySet].map((key, index) => {
    const sample = rows.find((row) => row[key] != null)?.[key];
    const override = getColumnOverride(table, key);
    const inferredType = override?.type ?? guessTypeFromValue(sample);
    const fkTable = override?.fkTable;
    const synthetic: DbColumnRow = {
      column_name: key,
      data_type: inferredType,
      udt_name: inferredType,
      is_nullable: "YES",
      column_default:
        key === "id" || override?.autoGenerated ? "gen_random_uuid()" : null,
      ordinal_position: index + 1,
      is_primary_key: Boolean(override?.primaryKey || key === "id"),
      foreign_table: fkTable ?? null,
      foreign_column: override?.fkValueKey ?? (fkTable ? "id" : null),
    };
    return mapDbColumnToDef(table, synthetic);
  });
}

export async function listLiveColumns(
  table: DashboardTableId,
): Promise<ColumnDef[]> {
  const supabase = createSupabaseAdminClient();
  const { data, error } = await supabase.rpc("dashboard_list_columns", {
    p_table: table,
  });

  if (!error) {
    return ((data ?? []) as DbColumnRow[]).map((row) =>
      mapDbColumnToDef(table, row),
    );
  }

  // Always fall back when schema RPCs are unavailable so table browsing works.
  if (isMissingRpcError(error)) {
    return inferColumnsFromRows(table);
  }

  // Unknown RPC failure — still try inference before giving up.
  try {
    return await inferColumnsFromRows(table);
  } catch {
    throw new Error(`Failed to load columns for ${table}: ${error.message}`);
  }
}

export async function addLiveColumn(input: {
  table: DashboardTableId;
  column: string;
  type: Exclude<ColumnType, "fk">;
  nullable?: boolean;
}) {
  const column = input.column.trim();
  if (!/^[a-z][a-z0-9_]*$/.test(column)) {
    throw new Error(
      "Column name must be lowercase snake_case and start with a letter.",
    );
  }

  const supabase = createSupabaseAdminClient();
  const { error } = await supabase.rpc("dashboard_add_column", {
    p_table: input.table,
    p_column: column,
    p_type: input.type,
    p_nullable: input.nullable ?? true,
  });

  if (error) {
    if (isMissingRpcError(error)) {
      throw new Error(SCHEMA_RPC_HINT);
    }
    throw new Error(
      `Failed to add column ${column} on ${input.table}: ${error.message}`,
    );
  }
}

export async function dropLiveColumn(input: {
  table: DashboardTableId;
  column: string;
}) {
  const columns = await listLiveColumns(input.table);
  const target = columns.find((column) => column.key === input.column);
  if (!target) {
    throw new Error(`Column does not exist: ${input.column}`);
  }
  if (target.protected || target.primaryKey) {
    throw new Error(
      `Column is protected and cannot be deleted: ${input.column}`,
    );
  }

  const supabase = createSupabaseAdminClient();
  const { error } = await supabase.rpc("dashboard_drop_column", {
    p_table: input.table,
    p_column: input.column,
  });

  if (error) {
    if (isMissingRpcError(error)) {
      throw new Error(SCHEMA_RPC_HINT);
    }
    throw new Error(
      `Failed to drop column ${input.column} on ${input.table}: ${error.message}`,
    );
  }
}

export async function probeSchemaRpc(): Promise<boolean> {
  const supabase = createSupabaseAdminClient();
  const { error } = await supabase.rpc("dashboard_list_columns", {
    p_table: "powerbi_groups",
  });
  if (!error) return true;
  return !isMissingRpcError(error);
}
