import type {
  ColumnDef,
  ColumnOverride,
  DashboardTableId,
  TableDef,
} from "@/lib/dashboard/types/tables";

const powerbiGroupsOverrides: ColumnOverride[] = [
  {
    key: "id",
    label: "ID",
    type: "uuid",
    primaryKey: true,
    required: true,
    protected: true,
  },
  { key: "name", label: "Name", required: true },
];

const powerbiDatasetsOverrides: ColumnOverride[] = [
  {
    key: "id",
    label: "ID",
    type: "uuid",
    primaryKey: true,
    required: true,
    protected: true,
  },
  {
    key: "workspace_id",
    label: "Workspace",
    type: "fk",
    required: true,
    fkTable: "powerbi_groups",
    fkLabelKey: "name",
  },
  { key: "name", label: "Name", required: true },
];

const reportQueriesOverrides: ColumnOverride[] = [
  {
    key: "id",
    label: "ID",
    type: "uuid",
    primaryKey: true,
    autoGenerated: true,
    protected: true,
  },
  { key: "report_page", label: "Report page", required: true },
  { key: "report_code", label: "Report code", required: true },
  { key: "report_type", label: "Report type", required: true },
  {
    key: "dataset_id",
    label: "Dataset",
    type: "fk",
    fkTable: "powerbi_datasets",
    fkLabelKey: "name",
  },
  { key: "dax_query", label: "DAX query", type: "longtext", required: true },
  {
    key: "WorkBook_Page_ID",
    label: "Workbook page",
    type: "fk",
    fkTable: "workbook_pages",
    fkLabelKey: "page_name",
  },
];

const salesSnapshotsOverrides: ColumnOverride[] = [
  {
    key: "id",
    label: "ID",
    type: "uuid",
    primaryKey: true,
    autoGenerated: true,
    protected: true,
  },
  {
    key: "report_query_id",
    label: "Report query",
    type: "fk",
    fkTable: "report_queries",
    fkLabelKey: "report_code",
  },
  {
    key: "workbook_id",
    label: "Workbook",
    type: "fk",
    fkTable: "workbooks",
    fkValueKey: "workbook_id",
    fkLabelKey: "workbook_name",
  },
];

const workbooksOverrides: ColumnOverride[] = [
  {
    key: "id",
    label: "ID",
    type: "uuid",
    primaryKey: true,
    autoGenerated: true,
    protected: true,
  },
  {
    key: "workbook_id",
    label: "Workbook ID",
    required: true,
    createOnly: true,
    protected: true,
  },
  { key: "workbook_name", label: "Workbook name", required: true },
  { key: "description", type: "longtext" },
  { key: "llm_context", type: "longtext" },
  { key: "pbi_calc_context", type: "longtext" },
  { key: "react_calc_context", type: "longtext" },
];

const workbookPagesOverrides: ColumnOverride[] = [
  {
    key: "id",
    label: "ID",
    type: "uuid",
    primaryKey: true,
    autoGenerated: true,
    protected: true,
  },
  {
    key: "workbook_id",
    label: "Workbook",
    type: "fk",
    fkTable: "workbooks",
    fkLabelKey: "workbook_name",
  },
  {
    key: "page_code",
    label: "Page code",
    required: true,
    createOnly: true,
    protected: true,
  },
  { key: "report_page", label: "Report page", required: true },
  { key: "page_name", label: "Page name", required: true },
  { key: "description", type: "longtext" },
  { key: "llm_context", type: "longtext" },
];

export const TABLE_CATALOG: Record<DashboardTableId, TableDef> = {
  powerbi_groups: {
    id: "powerbi_groups",
    name: "Power BI Groups",
    description: "Power BI workspaces synced into Supabase.",
    columnOverrides: powerbiGroupsOverrides,
    defaultOrderBy: { column: "name", ascending: true },
  },
  powerbi_datasets: {
    id: "powerbi_datasets",
    name: "Power BI Datasets",
    description: "Datasets linked to workspaces via workspace_id.",
    columnOverrides: powerbiDatasetsOverrides,
    defaultOrderBy: { column: "name", ascending: true },
  },
  report_queries: {
    id: "report_queries",
    name: "Report Queries",
    description: "DAX query catalog linked to datasets and workbook pages.",
    columnOverrides: reportQueriesOverrides,
    defaultOrderBy: { column: "report_code", ascending: true },
  },
  sales_snapshots: {
    id: "sales_snapshots",
    name: "Sales Snapshots",
    description: "Persisted sales snapshot rows by area and period.",
    columnOverrides: salesSnapshotsOverrides,
    defaultOrderBy: { column: "snapshot_date", ascending: false },
    canCreate: false,
    canEdit: false,
    canDelete: true,
  },
  workbooks: {
    id: "workbooks",
    name: "Workbooks",
    description: "Workbook definitions and calculation context.",
    columnOverrides: workbooksOverrides,
    defaultOrderBy: { column: "workbook_name", ascending: true },
  },
  workbook_pages: {
    id: "workbook_pages",
    name: "Workbook Pages",
    description: "Pages belonging to workbooks via workbook_id.",
    columnOverrides: workbookPagesOverrides,
    defaultOrderBy: { column: "sort_order", ascending: true },
  },
};

/** Stable sidebar / home order. */
export const TABLE_IDS: DashboardTableId[] = [
  "powerbi_groups",
  "powerbi_datasets",
  "workbooks",
  "workbook_pages",
  "report_queries",
  "sales_snapshots",
];

export function isDashboardTableId(value: string): value is DashboardTableId {
  return value in TABLE_CATALOG;
}

export function getTableDef(table: DashboardTableId): TableDef {
  return TABLE_CATALOG[table];
}

export function getColumnOverride(
  table: DashboardTableId,
  key: string,
): ColumnOverride | undefined {
  return TABLE_CATALOG[table].columnOverrides?.find(
    (column) => column.key === key,
  );
}

/** Identity fields managed by Supabase (or locked after insert). */
export function isNonEditableIdentityColumn(
  column: ColumnDef,
  mode: "create" | "edit",
): boolean {
  if (column.readOnly) return true;
  if (column.autoGenerated) return true;
  if (column.primaryKey && mode === "edit") return true;
  if (column.createOnly && mode === "edit") return true;
  return false;
}

export function getListColumnsFromDefs(columns: ColumnDef[]): ColumnDef[] {
  return columns.filter((column) => !column.readOnly);
}

export function getFormColumnsFromDefs(
  columns: ColumnDef[],
  mode: "create" | "edit",
): ColumnDef[] {
  return columns.filter(
    (column) => !isNonEditableIdentityColumn(column, mode),
  );
}

/** @deprecated Prefer live schema columns from the API. */
export function getListColumns(table: DashboardTableId): ColumnDef[] {
  return (TABLE_CATALOG[table].columnOverrides ?? []).map((column) => ({
    label: column.label ?? column.key,
    type: column.type ?? "text",
    ...column,
  }));
}

/** @deprecated Prefer live schema columns from the API. */
export function getFormColumns(
  table: DashboardTableId,
  mode: "create" | "edit",
): ColumnDef[] {
  return getFormColumnsFromDefs(getListColumns(table), mode);
}
