export type DashboardTableId =
  | "powerbi_groups"
  | "powerbi_datasets"
  | "report_queries"
  | "sales_snapshots"
  | "workbooks"
  | "workbook_pages";

export type ColumnType =
  | "uuid"
  | "text"
  | "longtext"
  | "boolean"
  | "number"
  | "date"
  | "datetime"
  | "fk";

export type ColumnDef = {
  key: string;
  label: string;
  type: ColumnType;
  required?: boolean;
  /** Show in the data table list view. */
  list?: boolean;
  /** Omit from create/edit forms (e.g. server timestamps). */
  readOnly?: boolean;
  /** Primary key — editable only on create when required and not auto-generated. */
  primaryKey?: boolean;
  /** Auto-generated by the database on insert (never editable). */
  autoGenerated?: boolean;
  /** Set on create only; locked when editing. */
  createOnly?: boolean;
  /** Column cannot be dropped from the dashboard. */
  protected?: boolean;
  fkTable?: DashboardTableId;
  /** Column used as the stored FK value. Defaults to `id`. */
  fkValueKey?: string;
  fkLabelKey?: string;
};

/** Optional per-column behavior layered on live DB schema. */
export type ColumnOverride = Partial<Omit<ColumnDef, "key">> & {
  key: string;
};

export type TableDef = {
  id: DashboardTableId;
  name: string;
  description: string;
  /** Behavior overrides merged onto live schema columns. */
  columnOverrides?: ColumnOverride[];
  defaultOrderBy?: { column: string; ascending?: boolean };
  /** Defaults to true. */
  canCreate?: boolean;
  /** Defaults to true. */
  canEdit?: boolean;
  /** Defaults to true. */
  canDelete?: boolean;
};

export type TableRow = Record<string, unknown>;

export type TableSummaryItem = {
  id: DashboardTableId;
  name: string;
  description: string;
  count: number;
};

export type TableListResponse = {
  ok: true;
  table: DashboardTableId;
  rows: TableRow[];
  total: number;
  page: number;
  pageSize: number;
  columns: ColumnDef[];
};

export type TableMutationResponse = {
  ok: true;
  row: TableRow;
};

export type FkOption = {
  id: string;
  label: string;
};

export type AddColumnRequest = {
  column: string;
  type: Exclude<ColumnType, "fk">;
  nullable?: boolean;
};
